export const SATP_MAINNET_PROGRAMS = {
  IDENTITY: "GTppU4E44BqXTQgbqMZ68ozFzhP1TLty3EGnzzjtNZfG",
  REVIEWS: "r9XX4frcqxxAZ6Au9V5PA3EAxs1zoNckqLLmoSRcNr4",
  REPUTATION: "2Lz7KzMvKdrGeAuS8WPHu7jK2yScrnKVgacpYVEuDjkJ",
  ATTESTATIONS: "6Xd1dAQJPvQRJ4Ntr6LtPTjDjPUZ8nfnmYLZaZ2DtrdD",
  VALIDATION: "6rYRiCYidJYV7QvKrzKGgNu4oMh6BAvynked69R7xMbV",
  ESCROW: "HXCUWKR2NvRcZ7rNAJHwPcH6QAAWaLR4bRFbfyuDND6C",
} as const;

export type SatpMainnetProgramName = keyof typeof SATP_MAINNET_PROGRAMS;
